#
# Copyright (c) 2019 Marcin Labenski
# MIT License
#

print("""
NOTE: This script needs python 3.2.2 - it won't work with 2.5.4

This tool gets string from loclang.hpp file from unrar source code
and generated two file in this dir:
1) loclangamiga.hpp - version of original loclang.hpp file that 
uses GetWString function to get localized string
2) unrar.cd - catalog definion file

Next, you can import unrar.cd into SimpleCat tool and create unrar.cs.
From that file in SimpleCat the following files can be generated:
1) unrar.cs 
2) localized catalog files (unrar.catalog).

""")

with open("/unrarsrc/loclang.hpp") as f:
	lines = f.readlines()

defs = {}

with open("unrar.cd", "w") as f0:
	with open("loclangamiga.hpp", "w") as f:
		f.write("//generated by generate_stubs.py script\n")
		f.write("// DO NOT EDIT\n\n")
		f.write("#define CATCOMP_NUMBERS\n")	
		f.write("#include \"unrar_locale.h\"\n")
		for line in lines:
			tokens = line.split()
			if tokens[0] != "#define":
				#print("!!!!! line %s skipped" % line)
				f.write(line)
				continue
			name = tokens[1]
			msg = "MSG_%s" % name
			tokens = line.split('L"')
			str = tokens[1][:-2]

			f0.write(";\n")
			f0.write("%s (//)\n" % msg)
			f0.write(str)
			f0.write("\n");
			
			f.write("#define %s GetWString(%s)\n" % (name, msg))
			
			
print("unrar.cd generated")
print("loclangamiga.hpp generated")
print("")
		
		
		
